<?php

/**
 * Maho
 *
 * @package    Maho_Mollie
 * @copyright  Copyright (c) 2026 Maho (https://mahocommerce.com)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

declare(strict_types=1);

class Maho_Mollie_Block_Adminhtml_System_Config_CredentialsChecker
    extends Mage_Adminhtml_Block_System_Config_Form_Field
{
    /**
     * Strip the scope controls — this field never stores a value.
     */
    #[\Override]
    public function render(\Maho\Data\Form\Element\AbstractElement $element)
    {
        $element->unsScope()->unsCanUseWebsiteValue()->unsCanUseDefaultValue();
        return parent::render($element);
    }

    /**
     * Render a "Test" button + result span. Submits the currently-entered
     * form values so the merchant can test keys before saving.
     */
    #[\Override]
    protected function _getElementHtml(\Maho\Data\Form\Element\AbstractElement $element)
    {
        $htmlId     = $element->getHtmlId();
        $buttonId   = $htmlId . '_button';
        $labelId    = $htmlId . '_label';
        $resultId   = $htmlId . '_result';
        $buttonLbl  = Mage::helper('maho_mollie')->__('Test API Key');
        $testingLbl = Mage::helper('maho_mollie')->__('Testing...');
        $errorLbl   = Mage::helper('maho_mollie')->__('An error occurred while testing the Mollie API key.');

        $ajaxUrl = Mage::getSingleton('adminhtml/url')->getUrl('adminhtml/mollie_credentials/test');

        // Form element IDs generated by system config — we read their values at click time.
        $liveKeyId = 'payment_maho_mollie_credentials_api_key_live';
        $testKeyId = 'payment_maho_mollie_credentials_api_key_test';
        $testmodeId = 'payment_maho_mollie_credentials_testmode';

        $html = <<<HTML
<style>
    #{$resultId} {
        display: none;
        margin-top: 8px;
        padding: 10px 14px;
        border-radius: 4px;
        font-size: 13px;
    }
    #{$resultId}.success {
        display: block;
        background: #ecfdf5;
        border: 1px solid #10b981;
    }
    #{$resultId}.error {
        display: block;
        background: #fef2f2;
        border: 1px solid #ef4444;
    }
</style>
<button type="button" class="scalable" id="{$buttonId}" onclick="mollieTestCredentials(); return false;">
    <span id="{$labelId}">{$buttonLbl}</span>
</button>
<div id="{$resultId}"></div>
<script>
    function mollieTestCredentials() {
        var button = document.getElementById('{$buttonId}');
        var label = document.getElementById('{$labelId}');
        var result = document.getElementById('{$resultId}');
        var liveEl = document.getElementById('{$liveKeyId}');
        var testEl = document.getElementById('{$testKeyId}');
        var modeEl = document.getElementById('{$testmodeId}');

        result.className = '';
        result.textContent = '';
        label.textContent = '{$testingLbl}';
        button.disabled = true;

        var data = new FormData();
        data.append('form_key', FORM_KEY);
        if (liveEl && !/^\*+$/.test(liveEl.value)) {
            data.append('api_key_live', liveEl.value);
        }
        if (testEl && !/^\*+$/.test(testEl.value)) {
            data.append('api_key_test', testEl.value);
        }
        if (modeEl) {
            data.append('testmode', modeEl.value);
        }

        mahoFetch('{$ajaxUrl}', {
            method: 'POST',
            body: data
        })
        .then(function(response) {
            result.textContent = response.message;
            result.className = response.success ? 'success' : 'error';
            label.textContent = '{$buttonLbl}';
            button.disabled = false;
        })
        .catch(function(err) {
            console.error('Mollie credentials test error:', err);
            result.textContent = '{$errorLbl}';
            result.className = 'error';
            label.textContent = '{$buttonLbl}';
            button.disabled = false;
        });
    }
</script>
HTML;

        return $html;
    }
}
